## 1. Import the Numpy Package

In [1]:
import numpy as np

## 2. Print the Numpy version and the configuration

In [2]:
print(np.__version__)

1.21.5


## 3. Create a vector of size 10

In [3]:
Z = np.zeros(10)
print(Z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


## 4. From the command, get the documentation of the Numpy's `add` function

In [4]:
!python -c "import numpy; numpy.info(numpy.add)"

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

## 5. Create a vector of size and make the 5th value as 1

In [5]:
Z = np.zeros(10)
Z[4] = 1
print(Z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


## 6. Create a vector, values ranging from 44 to 60

In [6]:
Z = np.arange(44, 61)
print(Z)

[44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60]


## 7. Reverse a vector, where as the first element becomes last and the last element becomes first

In [7]:
Z = np.arange(44, 61)
Z = Z[::-1]
print(Z)

[60 59 58 57 56 55 54 53 52 51 50 49 48 47 46 45 44]


## 8. Create a 3X3 matrix with values ranging from 0 to 8

In [8]:
Z = np.arange(40, 49).reshape(3, 3)
print(Z)

[[40 41 42]
 [43 44 45]
 [46 47 48]]


## 9. Find all indices of a non-zero element from a vector

In [9]:
Z = np.nonzero([1, 0, 2, 33, 0, 44, 0, 0])
print(Z)

(array([0, 2, 3, 5], dtype=int64),)


## 10. Create a Identity matrix - 3X3

In [10]:
Z = np.eye(3)
print(Z)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


## 11. Create a 3X3X3 - 3D Array with random values

In [11]:
Z = np.random.random((3, 3, 3))
print(Z)

[[[0.83211808 0.8079423  0.16569131]
  [0.09218174 0.64716254 0.20233437]
  [0.23702122 0.7254483  0.34616596]]

 [[0.39631801 0.41348031 0.93304974]
  [0.54997639 0.65000795 0.72763311]
  [0.30494131 0.76017986 0.23530656]]

 [[0.96782271 0.70491541 0.72626566]
  [0.80272799 0.44403129 0.8702657 ]
  [0.99767238 0.48770537 0.65891024]]]


## 12. Find the Minimum and Maximum value from a 10X10 array

In [12]:
Z = np.random.random((10, 10))
Zmin, Zmax = Z.min(), Z.max()
print("The complete Array : ", Z)
print("The minimum value is : ", Zmin)
print("The maximum value is : ", Zmax)

The complete Array :  [[0.2958794  0.77030315 0.97215249 0.07308444 0.59567642 0.68253964
  0.12803951 0.75620865 0.8280563  0.73738754]
 [0.10401196 0.9998486  0.21620737 0.55910858 0.30337629 0.29081644
  0.01283581 0.57985507 0.19428387 0.23692809]
 [0.36693568 0.51017371 0.88513722 0.99485074 0.77084832 0.78552084
  0.33659328 0.7438701  0.23256146 0.43930602]
 [0.82095154 0.13798872 0.21955288 0.80067511 0.47662598 0.14283544
  0.12298022 0.83848384 0.1625201  0.4793279 ]
 [0.86129613 0.92625691 0.86456785 0.7441115  0.78497484 0.55573109
  0.370773   0.85210783 0.90400411 0.11801549]
 [0.68492639 0.95050336 0.24799555 0.90406478 0.76680955 0.02079728
  0.04560651 0.44844443 0.39640567 0.72428661]
 [0.71200095 0.02581144 0.94857709 0.52035025 0.12029047 0.83356322
  0.93972421 0.31590232 0.74705654 0.41502354]
 [0.69708409 0.60920871 0.72119137 0.43841801 0.22674794 0.22018469
  0.29790362 0.7576634  0.97047577 0.18583254]
 [0.42293241 0.11711956 0.26772973 0.5381735  0.91239673 0

## 13. Find the Mean value from a vector of size 30

In [13]:
Z = np.random.random(30)
m = Z.mean()
print("The Array is : ", Z)
print("The mean value : ", m)

The Array is :  [0.74472276 0.26616903 0.5949012  0.90522737 0.7795277  0.5808411
 0.13298728 0.80963071 0.84206367 0.18657946 0.63513965 0.84539968
 0.91045415 0.33851723 0.92431462 0.90245908 0.50145788 0.63430517
 0.21659492 0.79534748 0.58015415 0.41434489 0.78582883 0.86317464
 0.09583568 0.60024806 0.79841597 0.65325077 0.76843218 0.71950545]
The mean value :  0.6275276918942339


## 14. Create a 2D array like this:

[[1, 1, 1, 1, 1]

 [1, 0, 0, 0, 1]
 
 [1, 0, 0, 0, 1]
 
 [1, 0, 0, 0, 1]
 
 [1, 1, 1, 1, 1]]

In [14]:
Z = np.ones((5, 5)) # Create a 5X5 array with all 1"
Z[1:-1, 1:-1] = 0 # Replace the inside values as 0 and keep the borders as 1
print(Z)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


# 15. Below operations on `NaN` are invalid

In [15]:
print("Zero mutiplied by a NaN is Invalid operation : ", 0 * np.nan)
print("NaN Comparisons are invalid : ", np.nan == np.nan)
print("Infinity and NaN comparisons are invalid : ", np.inf > np.nan)
print("Arithmeitc operations on NaN are invalid : ", np.nan - np.nan)

Zero mutiplied by a NaN is Invalid operation :  nan
NaN Comparisons are invalid :  False
Infinity and NaN comparisons are invalid :  False
Arithmeitc operations on NaN are invalid :  nan


# 16. A 5X5 matrix with 1,2,3,4 values positioned diagonaly

In [16]:
Z = np.diag(1+np.arange(4), k=-1) #The k value denotes the length of matrirx dimensions beyond the specified range 
print(Z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


# 17. Create a 8X8 Checkerboard

In [17]:
Z = np.zeros((8,8),dtype=int) #The 8X8 matrix is initialized with all Zeros
Z[1::2,::2] = 1 #Slice from the first row with 2 steps ahead and Slice all the columns with 2 steps ahead. Assign 1 to all the Sliced data
Z[::2,1::2] = 1 #Slice from the begining of the row with 2 steps ahead and slice from the first column with 2 steps ahead. Assign 1 to all the Sliced data
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


# 18. numpy.unravel_index - Converting a flat index or array of flat indices into a tuple of coordinates. What is the index of the 100th Element in a (6, 7, 8) array?

In [18]:
print(np.unravel_index(100,(6,7,8)))

(1, 5, 4)


# 19. Prepare 8X8 Checkerboard using the `Numpy Title` function

In [19]:
Z = np.tile(np.array([[0,1],[1,0]]), (4,4)) #The title function accepts the arrays - in this case a 2D Array [[0,1], [1,0]] and a dimension - 4,4
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


# 20. Normalize a 5X5 random matrix

In [20]:
Z = np.random.random((5,5))
print("Original matrix")
print(Z)
Zmax, Zmin = Z.max(), Z.min() #Max and Min value extraction
Z = (Z - Zmin)/(Zmax - Zmin) #Scaling formula
print("--------------------------")
print("Normalized matrix")
print(Z)

Original matrix
[[0.11183559 0.99345776 0.06550511 0.4206888  0.37094229]
 [0.0150907  0.39290237 0.52066896 0.5594389  0.25956519]
 [0.3739915  0.83545043 0.52752848 0.2709671  0.13969435]
 [0.56982403 0.82402811 0.98462681 0.124332   0.06139331]
 [0.36368691 0.6708102  0.33839442 0.37233064 0.82662895]]
--------------------------
Normalized matrix
[[0.09888404 1.         0.05152913 0.41456639 0.36371992]
 [0.         0.38616557 0.51675724 0.55638442 0.24988013]
 [0.36683655 0.83849892 0.52376843 0.26153415 0.1273588 ]
 [0.56699918 0.82682404 0.99097379 0.11165676 0.04732641]
 [0.35630411 0.67021829 0.33045238 0.36513897 0.8294824 ]]


# 21. Create a custom dtype that describes a color as four unsigned bytes (RGBA)

In [21]:
color = np.dtype([("r", np.ubyte, 1),
("g", np.ubyte, 1),
("b", np.ubyte, 1),
("a", np.ubyte, 1)])
print(color)

[('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')]


C:\Users\Bala\AppData\Local\Temp\ipykernel_14252\2754396101.py:1: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  color = np.dtype([("r", np.ubyte, 1),


# 22. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product)

In [22]:
matrix_1 = np.ones((5, 3)) # A 5X3 matrix
matrix_2 = np.ones((3, 2)) # A 3X2 matrix

Z = np.dot(matrix_1, matrix_2)
print("The Matrix multiplication result is : ")
print(Z)
print("The Shape of the resulting matrix is : ", Z.shape)

The Matrix multiplication result is : 
[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]
The Shape of the resulting matrix is :  (5, 2)


# 23. In a 1D Array negate all the elements between 3 and 8

In [23]:
Z = np.arange(11)
print("The Original 1D array is : ")
print(Z)
Z[(3 < Z) & (Z < 8)] *= -1 #Multiplying the elements between 3 and 8 by -1
print("Array after performing the negate operation in the 1D array : ")
print(Z)

The Original 1D array is : 
[ 0  1  2  3  4  5  6  7  8  9 10]
Array after performing the negate operation in the 1D array : 
[ 0  1  2  3 -4 -5 -6 -7  8  9 10]


# 24. Perform the arithmetic operations on the range functions

In [24]:
print(sum(range(5),-1)) 

#The range function - range(5) returns the numbers between 0 and 5 -> 0,1,2,3,4
#The -1 represents the axis

9


# 25. Power Expressions on the integer vector

In [25]:
Z = np.arange(1, 11)
print(Z)

print("Power Operations : ", Z**Z)  # 1**1, 2**2, 3**3, ...


[ 1  2  3  4  5  6  7  8  9 10]
Power Operations :  [         1          4         27        256       3125      46656
     823543   16777216  387420489 1410065408]


# 26. Arithmetic Operations on the Numpy Array

In [26]:
print(np.array(0) // np.array(0))
print(np.array(0) // np.array(0.))
print(np.array(0) / np.array(0))
print(np.array(0) / np.array(0.))

0
nan
nan
nan


C:\Users\Bala\AppData\Local\Temp\ipykernel_14252\2371707608.py:1: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))
C:\Users\Bala\AppData\Local\Temp\ipykernel_14252\2371707608.py:2: RuntimeWarning: invalid value encountered in floor_divide
  print(np.array(0) // np.array(0.))
C:\Users\Bala\AppData\Local\Temp\ipykernel_14252\2371707608.py:3: RuntimeWarning: invalid value encountered in true_divide
  print(np.array(0) / np.array(0))
C:\Users\Bala\AppData\Local\Temp\ipykernel_14252\2371707608.py:4: RuntimeWarning: invalid value encountered in true_divide
  print(np.array(0) / np.array(0.))


# 27. Rounding a Float Array

In [27]:
Z = np.random.uniform(-10,+10,10) #Extract 10 values ranging from -10 to +10
print("Original Array : ", Z)
print("Rounding the Original Array : ", np.trunc(Z + np.copysign(0.5, Z)))

Original Array :  [-2.68733548 -6.00954837 -7.7580291  -2.79703587 -3.24817341  5.33954795
  3.98096098 -4.94223403  5.99695543 -5.04794136]
Rounding the Original Array :  [-3. -6. -8. -3. -3.  5.  4. -5.  6. -5.]


# 28. Extract the Integer part of the Random array

In [28]:
Z = np.random.uniform(0,10,10) # Generate random 10 Integers from 0 to 10

print("Original Array : ")
print(Z)
print("**************************************")

# Approach-1 
decimal_portions = Z%1 # Extracts only the decimal portions
result = Z - decimal_portions # Subtract the decimal portions from the Original 1D Array
print("Approach-1, The Integer part of the Original Array : ")
print(result)
print("**************************************")

#Approach-2
result = np.floor(Z) # Using the Floor API from the Numpy library to extract the Integers
print("Approach-2, The Integer part of the Original Array : ")
print(result)
print("**************************************")

#Approach-3
result = np.ceil(Z) - 1 #Ceil will round off to the higher end value. from the higher end value subtracting by 1, we can get the integer part
print("Approach-3, The Integer part of the Original Array : ")
print(result)
print("**************************************")

#Approach-4
result = Z.astype(int) #Covert the data type from Flot to Integer
print("Approach-4, The Integer part of the Original Array : ")
print(result)
print("**************************************")

#Approach-5
result = np.trunc(Z) #Truncates the decimal part and returns the Integers
print("Approach-5, The Integer part of the Original Array : ")
print(result)
print("**************************************")

Original Array : 
[9.37776956 2.51557139 2.98214298 6.04350575 1.6022311  7.85394352
 3.12005495 0.08421555 1.59604212 1.49036907]
**************************************
Approach-1, The Integer part of the Original Array : 
[9. 2. 2. 6. 1. 7. 3. 0. 1. 1.]
**************************************
Approach-2, The Integer part of the Original Array : 
[9. 2. 2. 6. 1. 7. 3. 0. 1. 1.]
**************************************
Approach-3, The Integer part of the Original Array : 
[9. 2. 2. 6. 1. 7. 3. 0. 1. 1.]
**************************************
Approach-4, The Integer part of the Original Array : 
[9 2 2 6 1 7 3 0 1 1]
**************************************
Approach-5, The Integer part of the Original Array : 
[9. 2. 2. 6. 1. 7. 3. 0. 1. 1.]
**************************************


# 29. A 5X5 matrix with row values ranging from 0 to 4

In [29]:
Z1 = np.zeros((5,5))
Z2 = np.arange(5)
print("An Empty 5X5 matrix : ")
print(Z1)
print("A 1D array has values ranging from 0 to 4")
print(Z2)

print("Now creating a 5X5 with values ranging from 0 to 4")
result = Z1 + Z2 #Adding the 1D array (ranging from 0 to 4) to a 5X5 empty array
print(result)

An Empty 5X5 matrix : 
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
A 1D array has values ranging from 0 to 4
[0 1 2 3 4]
Now creating a 5X5 with values ranging from 0 to 4
[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


## 30. Use a custom function to populate the array of elements using the `numpy - fromiter` function

In [30]:
def generate():
    for x in range(10):
        yield x
#The fromiter API in the Numpy Library - Creates a new 1-dimensional array from an iterable object.
Z = np.fromiter(generate(),dtype=float,count=-1) #The -1 is a default value which reads all the data
print(Z)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


## 31. Create a vector of size 10 with values ranging from 0 to 1, excluding both the start and end values

In [31]:
#Returns evenly spaced numbers over the specified interval.
#[1:-1] this will exclude the start and end values and returns the rest of the data

Z = np.linspace(0,1,12,endpoint=True)[1:-1]
print(Z)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


## 32. Sort the vector of size 10

In [32]:
Z = np.random.random(10)
print("The Original array : ")
print(Z)
Z.sort() #Sorts the array
print("The Sorted array : ")
print(Z)

The Original array : 
[0.99340365 0.8816272  0.04215323 0.68826683 0.86504525 0.75720823
 0.06502149 0.35152618 0.46210598 0.15487457]
The Sorted array : 
[0.04215323 0.06502149 0.15487457 0.35152618 0.46210598 0.68826683
 0.75720823 0.86504525 0.8816272  0.99340365]


## 33. Alternate approach of Summing the Numpy Array apart from `np.sum` Function

In [33]:
Z = np.arange(15, 27)
print("The Original array : ")
print(Z)
print("The Sum is ", np.add.reduce(Z))

The Original array : 
[15 16 17 18 19 20 21 22 23 24 25 26]
The Sum is  246


## 34. Validate whether two Integer array are same or not

In [34]:
Z1 = np.random.randint(0,2,5)
Z2 = np.random.randint(0,2,5)

print("The Original Arrays : ")
print("Z1 : ")
print(Z1)
print("Z2 : ")
print(Z2)

result = np.allclose(Z1, Z2)
print("Validation result : ", result)

The Original Arrays : 
Z1 : 
[1 0 1 0 1]
Z2 : 
[1 1 0 1 1]
Validation result :  False


## 35. Make an Array read-only - Immutatble

In [35]:
Z = np.zeros(10)
Z.flags.writeable = False #The Flag writeable 
try:
    Z[0] = 1
except:
    print("Modifying the array fails")

Modifying the array fails


## 36. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates

In [36]:
Z = np.random.random((10,2))
X,Y = Z[:,0], Z[:,1]
R = np.sqrt(X**2+Y**2)
T = np.arctan2(Y,X)
print(R)
print(T)

[0.85162597 1.0319656  1.1549464  0.983893   1.02920374 0.85327478
 0.97718533 0.5228535  0.90464875 0.60696333]
[0.74860775 0.56614718 0.80378963 1.23931024 0.48988865 1.36591826
 0.65689961 0.93780228 0.57418799 1.31167359]


## 37. From a vector size of 10, identify the maximum value and replace it by Zero

In [37]:
Z = np.random.random(10)
print("The Original Array : ")
print(Z)
maximum_value = Z.argmax() #Identifying the maximum value
Z[maximum_value] = 0 #Replacing the maximum value by Zero
print("The Modified Array : ")
print(Z)

The Original Array : 
[0.07020114 0.06498463 0.11078498 0.14014401 0.75563923 0.5642596
 0.97431241 0.64593594 0.79656685 0.87857222]
The Modified Array : 
[0.07020114 0.06498463 0.11078498 0.14014401 0.75563923 0.5642596
 0.         0.64593594 0.79656685 0.87857222]


## 38. Create a structured array with x and y coordinates covering the [0,1]x[0,1] area

In [38]:
Z = np.zeros((10,10), [('x',float),('y',float)])
Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,10),
np.linspace(0,1,10))
print(Z)

[[(0.        , 0.        ) (0.11111111, 0.        )
  (0.22222222, 0.        ) (0.33333333, 0.        )
  (0.44444444, 0.        ) (0.55555556, 0.        )
  (0.66666667, 0.        ) (0.77777778, 0.        )
  (0.88888889, 0.        ) (1.        , 0.        )]
 [(0.        , 0.11111111) (0.11111111, 0.11111111)
  (0.22222222, 0.11111111) (0.33333333, 0.11111111)
  (0.44444444, 0.11111111) (0.55555556, 0.11111111)
  (0.66666667, 0.11111111) (0.77777778, 0.11111111)
  (0.88888889, 0.11111111) (1.        , 0.11111111)]
 [(0.        , 0.22222222) (0.11111111, 0.22222222)
  (0.22222222, 0.22222222) (0.33333333, 0.22222222)
  (0.44444444, 0.22222222) (0.55555556, 0.22222222)
  (0.66666667, 0.22222222) (0.77777778, 0.22222222)
  (0.88888889, 0.22222222) (1.        , 0.22222222)]
 [(0.        , 0.33333333) (0.11111111, 0.33333333)
  (0.22222222, 0.33333333) (0.33333333, 0.33333333)
  (0.44444444, 0.33333333) (0.55555556, 0.33333333)
  (0.66666667, 0.33333333) (0.77777778, 0.33333333)
  (0.8888

## 39. Construct Cauchy Matrix C.

## Formula: 1/(x_i - y_j)

In [39]:
X = np.arange(8) #Array with 8 elements from 0 to 7
Y = X + 0.5 #Create array Y from array X ust by increasing each element by 0.5
print("Array 1 : ", X)
print("*********************")
print("Array 2 : ", Y)
print("*********************")
C = 1.0 / np.subtract.outer(X, Y)
print(np.linalg.det(C))

Array 1 :  [0 1 2 3 4 5 6 7]
*********************
Array 2 :  [0.5 1.5 2.5 3.5 4.5 5.5 6.5 7.5]
*********************
3638.1636371179666


## 40. Minimum and Maximum representable value for each numpy Scalar type

In [40]:
print("The minimum representable value for ")
print("--------np.int8 : ", np.iinfo(np.int8).min)
print("--------np.int32 : ", np.iinfo(np.int32).min)
print("--------np.int64 : ", np.iinfo(np.int64).min)
print("--------------------------------------------------------")
print("The maximum representable value for ")
print("--------np.int8 : ", np.iinfo(np.int8).max)
print("--------np.int32 : ", np.iinfo(np.int32).max)
print("--------np.int64 : ", np.iinfo(np.int64).max)
print("--------------------------------------------------------")

The minimum representable value for 
--------np.int8 :  -128
--------np.int32 :  -2147483648
--------np.int64 :  -9223372036854775808
--------------------------------------------------------
The maximum representable value for 
--------np.int8 :  127
--------np.int32 :  2147483647
--------np.int64 :  9223372036854775807
--------------------------------------------------------


## 41. Print all the values of an Array

In [41]:
import sys
np.set_printoptions(threshold=sys.maxsize)
Z = np.zeros((25, 25))
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.

## 42. Find the closest value to a given scalar in an Array

In [42]:
Z = np.arange(100) #Construct values from 0 to 99 
v = np.random.uniform(0,100)
print(v)
index = (np.abs(Z-v)).argmin()
print(index)
print(Z[index])

99.53065183762723
99
99


# 43. A Structured array representing a position (x, y) and a color (r, g, b)

In [43]:
positions = [('x', float, 1),('y', float, 1)]
color = [('r', float, 1), ('g', float, 1), ('b', float, 1)]

Z = np.zeros(10, [('position', positions), ('color', color)])
print(Z)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


C:\Users\Bala\AppData\Local\Temp\ipykernel_14252\3575874729.py:4: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  Z = np.zeros(10, [('position', positions), ('color', color)])


# 44.A. Calculate the distance between two points. 

In [44]:
Z = np.random.random((10,2)) #A vector of size 10, 2. Representing 10 rows of x and y coordinates
X,Y = np.atleast_2d(Z[:,0]), np.atleast_2d(Z[:,1]) #Segregating the X and Y coordinates
D = np.sqrt((X-X.T)**2 + (Y-Y.T)**2)
print(D)

[[0.         0.43440695 0.19721642 0.48448806 0.28529814 0.48283056
  0.93393761 0.74051642 0.56279985 0.27591678]
 [0.43440695 0.         0.59762538 0.71402118 0.42064276 0.15747059
  0.82650495 0.74551073 0.51300626 0.24041113]
 [0.19721642 0.59762538 0.         0.3486618  0.28986436 0.60669332
  0.90965634 0.68269685 0.55911324 0.47116225]
 [0.48448806 0.71402118 0.3486618  0.         0.29448947 0.64104526
  0.64002857 0.3882989  0.37857733 0.70009896]
 [0.28529814 0.42064276 0.28986436 0.29448947 0.         0.36621036
  0.65064977 0.45751603 0.2825711  0.42420942]
 [0.48283056 0.15747059 0.60669332 0.64104526 0.36621036 0.
  0.67102569 0.60771887 0.37766056 0.36714853]
 [0.93393761 0.82650495 0.90965634 0.64002857 0.65064977 0.67102569
  0.         0.25423248 0.37195654 0.98538612]
 [0.74051642 0.74551073 0.68269685 0.3882989  0.45751603 0.60771887
  0.25423248 0.         0.23250462 0.85010008]
 [0.56279985 0.51300626 0.55911324 0.37857733 0.2825711  0.37766056
  0.37195654 0.23250

# 44.B. Calculate the distance between two points using `scipy` library

In [45]:
import scipy
import scipy.spatial

Z = np.random.random((10,2)) #A vector of size 10, 2. Representing 10 rows of x and y coordinates
D = scipy.spatial.distance.cdist(Z,Z)
print(D)

[[0.         0.82750863 0.54969416 0.26778667 0.27157681 0.61522768
  0.13792323 0.65723758 0.34497551 0.68719149]
 [0.82750863 0.         0.79300865 0.76058939 0.59155866 0.35631779
  0.92841479 0.18913735 0.49514821 0.57431497]
 [0.54969416 0.79300865 0.         0.28192735 0.6192444  0.82473416
  0.51188772 0.61437157 0.58923566 0.28543251]
 [0.26778667 0.76058939 0.28192735 0.         0.38454025 0.66865948
  0.25001608 0.5720595  0.39128248 0.45289451]
 [0.27157681 0.59155866 0.6192444  0.38454025 0.         0.34381503
  0.40307621 0.44700155 0.0998419  0.63714955]
 [0.61522768 0.35631779 0.82473416 0.66865948 0.34381503 0.
  0.74413747 0.32691578 0.28483271 0.71642235]
 [0.13792323 0.92841479 0.51188772 0.25001608 0.40307621 0.74413747
  0.         0.74916241 0.46553867 0.70211933]
 [0.65723758 0.18913735 0.61437157 0.5720595  0.44700155 0.32691578
  0.74916241 0.         0.34715999 0.42685986]
 [0.34497551 0.49514821 0.58923566 0.39128248 0.0998419  0.28483271
  0.46553867 0.34715

# 45. Convert a `float` array into `integer` array

In [46]:
Z = np.arange(10, dtype=np.float32)
print("Original Array - Float : ", Z)
Z = Z.astype(np.int32, copy=False)
print("Converted to Int : ")
print(Z)

Original Array - Float :  [0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
Converted to Int : 
[0 1 2 3 4 5 6 7 8 9]


# 46. Read `numpy` type of data from a file

In [47]:
Z = np.genfromtxt("files/program_46.txt", delimiter=",") #The missing values between the delimiters ',' are considered as NaN
print(Z)

[[ 1.  2.  3.  4.  5.]
 [ 6. nan nan  7.  8.]
 [nan nan  9. 10. 11.]]


# 47 `ndEnumerate`; `ndindex` to iterate the indices and values of each element in numpy array

In [48]:
Z = np.arange(9).reshape(3,3) #Array definition 
print("The initialized Array : ")
print(Z)
print("----------------------------------------")
for index, value in np.ndenumerate(Z):
    print("Index : ", index, " | Value : ", value)
print("----------------------------------------")
for index in np.ndindex(Z.shape):
    print("Index : ", index, " | Value : ", Z[index])

The initialized Array : 
[[0 1 2]
 [3 4 5]
 [6 7 8]]
----------------------------------------
Index :  (0, 0)  | Value :  0
Index :  (0, 1)  | Value :  1
Index :  (0, 2)  | Value :  2
Index :  (1, 0)  | Value :  3
Index :  (1, 1)  | Value :  4
Index :  (1, 2)  | Value :  5
Index :  (2, 0)  | Value :  6
Index :  (2, 1)  | Value :  7
Index :  (2, 2)  | Value :  8
----------------------------------------
Index :  (0, 0)  | Value :  0
Index :  (0, 1)  | Value :  1
Index :  (0, 2)  | Value :  2
Index :  (1, 0)  | Value :  3
Index :  (1, 1)  | Value :  4
Index :  (1, 2)  | Value :  5
Index :  (2, 0)  | Value :  6
Index :  (2, 1)  | Value :  7
Index :  (2, 2)  | Value :  8


# 48. Generate a generic 2D Gaussian like array

In [49]:
X, Y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10)) #Meshgrid - Make N-D coordinate arrays for vectorized evaluations of N-D scalar/vector fields over N-D grids, given one-dimensional coordinate arrays x1, x2,…, xn.
D = np.sqrt(X*X + Y*Y)
sigma, mu = 1.0, 0.0
G = np.exp(-( (D-mu)**2 / (2.0 * sigma**2 )))
print(G)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

# 49. Randomly place 'p' elements in a 2D array

In [50]:
n = 10
p = 3
Z = np.zeros((n,n))
print("Initialized Array : ")
print(Z)
np.put(Z, np.random.choice(range(n*n), p, replace=False),1)
print("The array after replacement : ")
print(Z)

Initialized Array : 
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
The array after replacement : 
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


# 50. Subtract each row value by the mean

In [51]:
X = np.random.rand(5, 10) # The original array
print("The original array ")
print(X)

X_mean = X.mean(axis=1, keepdims=True)
Y = X - X_mean
print("The array after the mean subtraction operation")
print(Y)

The original array 
[[0.80111952 0.69810258 0.86997856 0.24160539 0.15755288 0.20920914
  0.25484325 0.69933445 0.96211725 0.62346218]
 [0.06014016 0.63454604 0.00441795 0.87312089 0.03097638 0.26467338
  0.74937507 0.25885846 0.83059794 0.20575574]
 [0.13046013 0.01789004 0.93704516 0.39867322 0.26781533 0.11719851
  0.73156476 0.6526963  0.732535   0.28778275]
 [0.4400236  0.85893156 0.38957532 0.68126959 0.21796101 0.5534262
  0.89646344 0.36475527 0.7730209  0.54404822]
 [0.94907734 0.22166478 0.24454709 0.10876588 0.16505258 0.04245232
  0.3907293  0.75300098 0.73495298 0.20195478]]
The array after the mean subtraction operation
[[ 0.249387    0.14637006  0.31824604 -0.31012713 -0.39417964 -0.34252338
  -0.29688927  0.14760193  0.41038473  0.07172966]
 [-0.33110604  0.24329984 -0.38682825  0.48187469 -0.36026982 -0.12657282
   0.35812887 -0.13238774  0.43935174 -0.18549046]
 [-0.29690599 -0.40947608  0.50967904 -0.0286929  -0.15955079 -0.31016761
   0.30419864  0.22533018  0.30516

# 51. Sort an Array

In [52]:
Z = np.array([3, 2, 0, 1]) #Initialize a 3X3 array
print("Original Array:")
print(Z)
print("-------------------------------------------------")
Z_Sorted = np.sort(Z)
print("Sorted Array:")
print(Z_Sorted)

Original Array:
[3 2 0 1]
-------------------------------------------------
Sorted Array:
[0 1 2 3]


# 52. Validate if a given 2D array has `null` columns

In [53]:
Z = np.random.randint(0,3,(3,10)) # Initialize random array
print("Initialized array :")
print(Z)
print((~Z.any(axis=0)).any())

Initialized array :
[[2 1 2 2 0 2 0 1 1 0]
 [1 1 2 1 1 0 2 1 1 2]
 [2 2 2 1 0 2 1 2 2 0]]
False


# 53. Find the nearest value from a given value in an Array

In [54]:
Z = np.random.uniform(0,1,10)
print("Initialized array :")
print(Z)
value = 1.0
abs_value = np.abs(Z - value) #The abs() function returns the absolute value of the specified number.
arg_min_value = abs_value.argmin() #The numpy.argmin() returns indices of the min element of the array in a particular axis. 
m = Z.flat[arg_min_value] #Flattens the array and finds the nearest value
print("The Nearest value : ", m)

Initialized array :
[0.94332795 0.35105809 0.64617664 0.14457404 0.96809724 0.6063473
 0.65088382 0.86861708 0.54627445 0.79235091]
The Nearest value :  0.9680972434473173


# 54. Create an array class that has a `name` attribute

In [55]:
class NamedArray(np.ndarray):
    
    def __new__(cls, array, name="default_name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    
    def __array_finalize__(self, obj):
        if obj is None:
            return
        self.info = getattr(obj, 'name', "default_name")

Z = NamedArray(np.arange(10), "range_10") #Initialize the instance of NamedArray
print(Z.name) 

range_10


# 55. Add 1 to each element in a vector. indexed by a second vector

In [56]:
Z = np.ones(10) #Initialize array with all 1s, size of 10
print("Original Array - 1st : ")
print(Z)
print("-----------------------------------------------------------------------------------------------------")
I = np.random.randint(0, len(Z), 20) #The vector holds 10 (Length of the Z array) random values between 0 and 20
print("The Second array : ")
print(I)
print("-----------------------------------------------------------------------------------------------------")
'''
The np.bincount() is a numpy library method used to obtain the frequency of each element provided inside a numpy array. 
The numpy bincount() method takes arr_name, weights, and minlength as arguments and returns the ndarray of integers.
'''
bin_count = np.bincount(I, minlength=len(Z))
print("The bin_count : ")
print(bin_count)
print("-----------------------------------------------------------------------------------------------------")
result = Z + bin_count
print("Result after the summation")
print(result)
print("-----------------------------------------------------------------------------------------------------")

Original Array - 1st : 
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
-----------------------------------------------------------------------------------------------------
The Second array : 
[2 4 9 8 0 1 7 0 3 7 4 2 3 5 5 1 0 1 9 9]
-----------------------------------------------------------------------------------------------------
The bin_count : 
[3 3 2 2 2 2 0 2 1 3]
-----------------------------------------------------------------------------------------------------
Result after the summation
[4. 4. 3. 3. 3. 3. 1. 3. 2. 4.]
-----------------------------------------------------------------------------------------------------


# 56. Accumulate elements of a vector (X) to an array (F) based on an index list (I)?

In [57]:
X = [1,2,3,4,5,6]
print("X Array : ")
print(X)
print("--------------------------------------------------")
I = [1,3,9,3,4,1]
print("I Array : ")
print(I)
print("--------------------------------------------------")
F = np.bincount(I, X)
print(F)

X Array : 
[1, 2, 3, 4, 5, 6]
--------------------------------------------------
I Array : 
[1, 3, 9, 3, 4, 1]
--------------------------------------------------
[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


# 57. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors

In [58]:
w,h = 16,16
I = np.random.randint(0,2,(h,w,3)).astype(np.ubyte) #numpy.ubyte - Unsigned integer type, compatible with C unsigned char.
F = I[...,0]*256*256 + I[...,1]*256 +I[...,2]
n = len(np.unique(F))
print(np.unique(I))

[0 1]


# 58. In a 4D array, get the sum over the last two axis at once

In [59]:
A = np.random.randint(0,10,(3,4,3,4))
print("Initialized Array : ")
print(A)
print("------------------------------------------------------")
sum = A.reshape(A.shape[:-2] + (-1,)).sum(axis=-1)
print(sum)

Initialized Array : 
[[[[7 9 4 3]
   [8 5 3 0]
   [9 6 5 3]]

  [[3 7 7 7]
   [6 4 4 8]
   [7 1 5 8]]

  [[4 7 6 1]
   [5 1 4 1]
   [6 1 0 4]]

  [[1 5 4 0]
   [3 8 4 3]
   [9 9 7 6]]]


 [[[6 6 7 2]
   [9 6 6 8]
   [5 1 6 1]]

  [[3 1 2 4]
   [3 6 3 2]
   [9 0 8 8]]

  [[6 3 4 0]
   [2 8 7 8]
   [5 3 6 2]]

  [[2 8 6 3]
   [6 3 5 9]
   [3 1 5 0]]]


 [[[2 8 7 0]
   [5 8 0 6]
   [9 2 3 3]]

  [[5 2 6 8]
   [2 9 9 0]
   [6 8 0 2]]

  [[6 5 3 9]
   [0 2 1 6]
   [7 7 4 6]]

  [[2 7 4 6]
   [2 5 7 5]
   [5 8 0 2]]]]
------------------------------------------------------
[[62 67 40 59]
 [63 49 54 51]
 [53 57 56 53]]


# 59. In a 1D Vecotor `D`, compute means of subsets of `D` using a vector `S` of same size describing subset indices

In [60]:
D = np.random.uniform(0,1,100)
print("Initialized Array D : ")
print(D)
print("------------------------------------------------------")
S = np.random.randint(0,10,100)
print("Initialized Array S : ")
print(S)
print("------------------------------------------------------")
D_sums = np.bincount(S, weights=D)
print(D_sums)
D_counts = np.bincount(S)
print("The counts of each element from the vector S : ", D_counts)
print("------------------------------------------------------")
D_means = D_sums / D_counts
print("The mean value : ", D_means)

Initialized Array D : 
[0.33429302 0.11371275 0.08507687 0.62068783 0.25217231 0.24479989
 0.61752086 0.84547516 0.65387376 0.1966771  0.61299456 0.27990846
 0.83044666 0.42660103 0.549263   0.57974964 0.3242861  0.4016818
 0.03239742 0.44769817 0.1577528  0.46316215 0.16976322 0.02064916
 0.65031563 0.65931645 0.79526573 0.9192546  0.46358898 0.65508135
 0.78645783 0.14852164 0.53655458 0.12742841 0.76890525 0.22544407
 0.39403367 0.23319425 0.47268076 0.98232052 0.73312289 0.77331653
 0.18891503 0.78540651 0.74826383 0.09982746 0.56040328 0.85207855
 0.91480435 0.05105901 0.36657518 0.11682669 0.54479499 0.60501656
 0.57272683 0.34425954 0.32399815 0.05226367 0.17804256 0.24241578
 0.0984964  0.70725413 0.79652205 0.73466503 0.21898523 0.83758857
 0.55071857 0.63797803 0.41798045 0.31410235 0.30367539 0.69237133
 0.98940373 0.51832525 0.31889521 0.77521504 0.9931425  0.72973382
 0.72483451 0.43851286 0.40281986 0.16009293 0.7707933  0.8462659
 0.5341591  0.85220242 0.98656782 0.54001

# 60. Get the diagonal of a dot product

In [61]:
A = np.random.rand(3, 3)
B = np.random.rand(3, 3)

print("Array A : ")
print(A)
print("------------------------------------------------------")

print("Array B : ")
print(B)
print("------------------------------------------------------")

result = np.diag(np.dot(A, B))
print(result)

Array A : 
[[0.67702736 0.14856685 0.70755652]
 [0.06833949 0.97987203 0.23645703]
 [0.83123298 0.73338085 0.04311305]]
------------------------------------------------------
Array B : 
[[0.24665211 0.4314887  0.1728591 ]
 [0.81602279 0.94341164 0.81594546]
 [0.053612   0.18445698 0.81381463]]
------------------------------------------------------
[0.32615768 0.99752654 0.77717099]


# 61. From the vector `[1, 2, 3, 4, 5]`, build a new vector with 3 consecutive zeros interleaved between each value

In [62]:
Z = np.array([1,2,3,4,5])
nz = 3 #Number of zeros should be placed between each value in the vector
Z_len = len(Z)
print("Length of Z : ", Z_len)
print("------------------------------------------------------")
Z0 = np.zeros(Z_len + (Z_len-1)*(nz)) #Initializing a Zero vector of size (Length of the vector + the number of zeros between each value)
print("Zero Array : ")
print(Z0)
print("------------------------------------------------------")
Z0[::nz+1] = Z
print(Z0)

Length of Z :  5
------------------------------------------------------
Zero Array : 
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
------------------------------------------------------
[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


# 62. Multiply two arrays. Array1 of dimension 5X5X3 and Array2 of dimension 5X5

In [63]:
A = np.ones((5,5,3))
print("Array A : ")
print(A)
print("------------------------------------------------------")
B = 2*np.ones((5,5))
print("Array B : ")
print(B)
print("------------------------------------------------------")
print("Multiplication between A and B :")
print(A * B[:,:,None])

Array A : 
[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]
------------------------------------------------------
Array B : 
[[2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]]
------------------------------------------------------
Multiplication between A and B :
[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


# 63. Swap two rows of an Array

In [64]:
A = np.arange(25).reshape(5,5)
print("Initialized Array")
print(A)
print("------------------------------------------------------")
print("Swap array rows 0th and 1st Index")
A[[0, 1]] = A[[1, 0]]
print(A)

Initialized Array
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
------------------------------------------------------
Swap array rows 0th and 1st Index
[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


# 64. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the triangles

In [65]:
faces = np.random.randint(0,100,(10,3))
F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
F = F.reshape(len(F)*3,2)
F = np.sort(F,axis=1)
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
G = np.unique(G)
print(G)

[( 3, 75) ( 3, 76) ( 8, 50) ( 8, 93) (10, 42) (10, 92) (11, 42) (11, 94)
 (14, 15) (14, 83) (15, 83) (21, 40) (21, 60) (23, 47) (23, 53) (31, 63)
 (31, 69) (33, 36) (33, 96) (36, 96) (38, 41) (38, 68) (40, 60) (41, 68)
 (42, 92) (42, 94) (47, 53) (50, 93) (63, 69) (75, 76)]


# 65. Given an array C that is a bincount, how to produce an array A such that `np.bincount(A) == C`?

In [66]:
C = np.bincount([1,1,2,3,4,4,6])
print("C Array")
print(C)
print("------------------------------------------------------")
A = np.repeat(np.arange(len(C)), C)
print(A)

C Array
[0 2 1 1 2 0 1]
------------------------------------------------------
[1 1 2 3 4 4 6]


# 66. Compute Averages using a sliding window over an array

In [67]:
def moving_average(a, n=3) :
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n
Z = np.arange(20)
print("Initialized Array")
print(Z)
print("------------------------------------------------------")
print("Array after moving average")
print(moving_average(Z, n=3))

Initialized Array
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
------------------------------------------------------
Array after moving average
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


# 67. Consider a onedimensional array Z, build a twodimensional array whose first row is `(Z[0],Z[1],Z[2])` and each subsequent row is shifted by 1 (last row  should be `(Z[3], Z[2], Z[1])`

In [68]:
from numpy.lib import stride_tricks

def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.itemsize, a.itemsize)
    return stride_tricks.as_strided(a, shape=shape, strides=strides)

Z = rolling(np.arange(10), 3)
print(Z)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


# 68.Negate a `boolean`

In [69]:
Z = np.random.randint(0,2,100)
print("Initialized Array ")
print(Z)
print("------------------------------------------------------")
print("Result after negation")
result = np.logical_not(Z, out=Z)
print(result)

Initialized Array 
[1 0 1 0 1 0 0 0 0 0 1 0 0 0 0 1 0 1 0 1 0 1 0 0 0 1 1 0 0 0 0 0 1 1 0 1 0
 1 0 1 1 0 0 1 0 0 1 1 1 1 0 0 0 0 1 1 0 0 0 1 1 0 1 1 1 1 1 1 0 0 1 0 1 1
 1 1 1 0 0 0 0 1 1 0 0 0 0 1 1 1 0 1 0 0 0 0 0 0 1 0]
------------------------------------------------------
Result after negation
[0 1 0 1 0 1 1 1 1 1 0 1 1 1 1 0 1 0 1 0 1 0 1 1 1 0 0 1 1 1 1 1 0 0 1 0 1
 0 1 0 0 1 1 0 1 1 0 0 0 0 1 1 1 1 0 0 1 1 1 0 0 1 0 0 0 0 0 0 1 1 0 1 0 0
 0 0 0 1 1 1 1 0 0 1 1 1 1 0 0 0 1 0 1 1 1 1 1 1 0 1]


# 69. Consider 2 sets of points `P0`,`P1` describing lines (2d) and a point `p`, how to compute distance from `p` to each line `i` `(P0[i],P1[i])`?

In [70]:
def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))

P0 = np.random.uniform(-10,10,(10,2))
print("Point P0")
print(P0)
print("------------------------------------------------------")
P1 = np.random.uniform(-10,10,(10,2))
print("Point P1")
print(P1)
print("------------------------------------------------------")
p = np.random.uniform(-10,10,( 1,2))
print("Point p")
print(p)
print("------------------------------------------------------")
distance_result = distance(P0, P1, p)
print(distance_result)

Point P0
[[-0.05312987 -1.5136354 ]
 [ 5.56810176  1.79087691]
 [ 5.36945111 -3.53473114]
 [-6.69586591  7.55041497]
 [ 9.87440277 -2.92390661]
 [-7.83606142 -0.27031523]
 [-9.99057497  8.74552328]
 [-7.34977122 -8.51067217]
 [-6.76997123  0.63453712]
 [-8.36731298 -0.52197313]]
------------------------------------------------------
Point P1
[[ 8.82386535  8.2363272 ]
 [-9.31191405 -4.24885611]
 [-7.63744453  5.86395789]
 [ 3.70789079 -4.52704432]
 [ 4.98807533  0.14044622]
 [ 5.84464979 -3.78203314]
 [-9.125038   -5.43410052]
 [ 2.59140763  6.329828  ]
 [ 1.571375    2.32629201]
 [ 3.26664006 -0.70459582]]
------------------------------------------------------
Point p
[[2.7181031  7.84079173]]
------------------------------------------------------
[ 4.24852424  6.6776071   7.66741555  7.32204143  5.31760871 10.48049382
 12.62994479  0.73565099  5.17653216  8.53572539]


# 70. Consider 2 sets of points `P0`,`P1` describing lines (2d) and a set of points `P`, how to compute distance from each point `j` `(P[j])` to each line `i` `(P0[i],P1[i])`?

In [71]:
P0 = np.random.uniform(-10, 10, (10,2))
print("Point P0")
print(P0)
print("------------------------------------------------------")
P1 = np.random.uniform(-10,10,(10,2))
print("Point P1")
print(P1)
print("------------------------------------------------------")
p = np.random.uniform(-10, 10, (10,2))
print(np.array([distance(P0,P1,p_i) for p_i in p]))

Point P0
[[ 6.3628778   7.75044202]
 [-8.61651201 -8.63062632]
 [-1.58372698  1.85326638]
 [-1.13163668 -8.16307174]
 [-9.95194463  5.84542181]
 [-3.71113365  7.65149546]
 [-2.89188081 -7.03332904]
 [-7.85149898 -2.74739672]
 [-8.673302    2.83798362]
 [-1.88726765 -0.28895444]]
------------------------------------------------------
Point P1
[[ 0.19996416  8.84447599]
 [ 8.66696699  9.01506693]
 [ 2.04446548 -4.60873658]
 [-5.80520327 -5.58392024]
 [-8.77445325  9.39108586]
 [ 1.05766141 -3.30425316]
 [-5.76537562 -0.47253017]
 [ 0.88491062  3.99390696]
 [-2.401969    3.47620669]
 [-5.91143943  5.16140532]]
------------------------------------------------------
[[ 7.28156936  2.92831909  4.80512328 10.49843321 15.43369447  4.82626967
   9.94514709  4.89644746  3.50039942  5.78145552]
 [ 2.5386911   0.1109991   7.68141305 14.93212661 14.57862115  7.30702336
  12.43507465  1.57860169  1.10854721  9.1038893 ]
 [14.20782454 10.16036126  3.52336625  5.2421721  20.41868259  4.34892738
   9.4

# 71. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a fill value when necessary)

In [72]:
Z = np.random.randint(0,10,(10,10))
shape = (5,5)
fill = 0
position = (1,1)

R = np.ones(shape, dtype=Z.dtype)*fill
P = np.array(list(position)).astype(int)
Rs = np.array(list(R.shape)).astype(int)
Zs = np.array(list(Z.shape)).astype(int)

R_start = np.zeros((len(shape),)).astype(int)
R_stop = np.array(list(shape)).astype(int)
Z_start = (P-Rs//2)
Z_stop = (P+Rs//2)+Rs%2

R_start = (R_start - np.minimum(Z_start,0)).tolist()
Z_start = (np.maximum(Z_start,0)).tolist()
R_stop = np.maximum(R_start, (R_stop - np.maximum(Z_stop-Zs,0))).tolist()
Z_stop = (np.minimum(Z_stop,Zs)).tolist()

r = [slice(start,stop) for start,stop in zip(R_start,R_stop)]
z = [slice(start,stop) for start,stop in zip(Z_start,Z_stop)]
R[r] = Z[z]

print(Z)
print(R)

[[9 0 5 2 1 0 8 1 9 2]
 [1 3 7 8 9 8 4 4 0 1]
 [9 6 9 3 6 1 7 9 5 6]
 [8 9 1 0 9 2 6 8 5 8]
 [2 4 7 5 8 4 7 9 7 0]
 [8 7 5 5 2 2 0 4 9 9]
 [2 6 5 8 4 6 7 0 3 9]
 [4 3 4 6 7 2 1 1 4 3]
 [5 4 5 7 5 7 7 3 7 0]
 [7 7 7 9 8 1 0 8 8 0]]
[[0 0 0 0 0]
 [0 9 0 5 2]
 [0 1 3 7 8]
 [0 9 6 9 3]
 [0 8 9 1 0]]


C:\Users\Bala\AppData\Local\Temp\ipykernel_14252\1035071397.py:23: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  R[r] = Z[z]


# 72. Consider an array `Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14]`, how to generate an array `R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]` ? 

In [73]:
Z = np.arange(1,15,dtype=np.int32)
print("Initialized Array : ")
print(Z)
print("------------------------------------------------------")
R = stride_tricks.as_strided(Z,(11,4),(4,4))
print("The result after applying Strides : ")
print(R)

Initialized Array : 
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14]
------------------------------------------------------
The result after applying Strides : 
[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


# 73. Matrix `rank` computation

In [74]:
Z = np.random.uniform(0,1,(10,10))
print("Initialized Array : ")
print(Z)
print("------------------------------------------------------")
U, S, V = np.linalg.svd(Z) # Singular Value Decomposition
rank = np.sum(S > 1e-10)
print("Rank is : ", rank)

Initialized Array : 
[[0.31084249 0.80432083 0.87203705 0.20529497 0.01142092 0.55665127
  0.71538675 0.95905376 0.25714771 0.0213163 ]
 [0.69214096 0.94663588 0.18782814 0.4666368  0.36890114 0.49412008
  0.7132778  0.05054471 0.84082814 0.07246721]
 [0.65502159 0.34428952 0.57034097 0.89209928 0.60347892 0.42758065
  0.73386666 0.10537604 0.69056206 0.72914857]
 [0.44937984 0.46495325 0.87673874 0.61095574 0.62118266 0.90142667
  0.31623426 0.51088184 0.75093097 0.07063916]
 [0.70894968 0.18363379 0.34985004 0.90699374 0.56791791 0.98882421
  0.78139237 0.82131857 0.616056   0.2092135 ]
 [0.03900103 0.08098534 0.87076217 0.04925728 0.37287823 0.53156027
  0.24029318 0.07984821 0.73432902 0.23891631]
 [0.11045387 0.60382026 0.80278862 0.24807748 0.62910999 0.97843326
  0.77050175 0.64197997 0.51852287 0.90455748]
 [0.09047157 0.36317746 0.46717038 0.39154307 0.82427924 0.32311431
  0.57396846 0.20821184 0.99396141 0.58729055]
 [0.64936422 0.86396086 0.63260492 0.18672603 0.96859312 0.

# 74. Find the most frequent value in an Array

In [75]:
Z = np.random.randint(0,10,100)
print("Initialized Array : ")
print(Z)
print("------------------------------------------------------")
frequent_value = np.bincount(Z).argmax()
print(frequent_value)

Initialized Array : 
[6 7 7 0 9 3 5 7 4 1 5 0 8 7 1 5 3 6 1 2 6 8 8 5 9 3 2 2 5 2 7 6 1 9 3 7 3
 3 1 9 4 7 6 4 0 0 7 9 6 1 8 9 2 1 1 7 7 1 0 9 6 1 2 5 8 1 6 9 1 4 4 4 5 4
 3 7 7 8 5 0 2 3 7 1 2 7 5 3 6 3 0 4 4 6 8 1 6 8 8 8]
------------------------------------------------------
1


# 75. Extract all the contiguous 3x3 blocks from a random 10x10 matrix

In [76]:
Z = np.random.randint(0,5,(10,10))
print("Initialized Array : ")
print(Z)
print("------------------------------------------------------")
n = 3
i = 1 + (Z.shape[0]-3)
j = 1 + (Z.shape[1]-3)
C = stride_tricks.as_strided(Z, shape=(i, j, n, n), strides=Z.strides + Z.strides)
print(C)

Initialized Array : 
[[3 2 4 4 1 3 3 4 0 1]
 [0 2 4 0 1 4 1 2 4 2]
 [2 1 0 1 0 4 1 4 4 2]
 [1 3 4 2 3 4 1 1 3 1]
 [4 1 0 2 4 3 1 0 4 1]
 [2 1 1 3 2 0 3 3 2 3]
 [4 4 4 3 1 0 3 4 1 3]
 [2 4 3 3 0 1 2 0 1 3]
 [0 1 3 3 2 0 4 4 0 1]
 [3 1 2 3 0 3 3 1 0 3]]
------------------------------------------------------
[[[[3 2 4]
   [0 2 4]
   [2 1 0]]

  [[2 4 4]
   [2 4 0]
   [1 0 1]]

  [[4 4 1]
   [4 0 1]
   [0 1 0]]

  [[4 1 3]
   [0 1 4]
   [1 0 4]]

  [[1 3 3]
   [1 4 1]
   [0 4 1]]

  [[3 3 4]
   [4 1 2]
   [4 1 4]]

  [[3 4 0]
   [1 2 4]
   [1 4 4]]

  [[4 0 1]
   [2 4 2]
   [4 4 2]]]


 [[[0 2 4]
   [2 1 0]
   [1 3 4]]

  [[2 4 0]
   [1 0 1]
   [3 4 2]]

  [[4 0 1]
   [0 1 0]
   [4 2 3]]

  [[0 1 4]
   [1 0 4]
   [2 3 4]]

  [[1 4 1]
   [0 4 1]
   [3 4 1]]

  [[4 1 2]
   [4 1 4]
   [4 1 1]]

  [[1 2 4]
   [1 4 4]
   [1 1 3]]

  [[2 4 2]
   [4 4 2]
   [1 3 1]]]


 [[[2 1 0]
   [1 3 4]
   [4 1 0]]

  [[1 0 1]
   [3 4 2]
   [1 0 2]]

  [[0 1 0]
   [4 2 3]
   [0 2 4]]

  [[1 0 4]
   [2 3 4]
  

# 76. Convert a `numpy` array into `dictionary`

In [77]:
a = np.array([['a', 'b', 'c'],
                  ['d', 'e', 'f'],
                  ['g', 'h', 'i']])

print("Initialized Array : ")
print(a)
print("Type : ", type(a))
print("------------------------------------------------------")
d = dict(enumerate(a.flatten(), 1))
print("Converted to dictionary : ")
print(d)
print("Type : ", type(d))

Initialized Array : 
[['a' 'b' 'c']
 ['d' 'e' 'f']
 ['g' 'h' 'i']]
Type :  <class 'numpy.ndarray'>
------------------------------------------------------
Converted to dictionary : 
{1: 'a', 2: 'b', 3: 'c', 4: 'd', 5: 'e', 6: 'f', 7: 'g', 8: 'h', 9: 'i'}
Type :  <class 'dict'>


# 77. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1))

In [78]:
p, n = 2, 5
M = np.ones((p,n,n))
V = np.ones((p,n,1))
S = np.tensordot(M, V, axes=[[0, 2], [0, 1]])
print(S)

[[10.]
 [10.]
 [10.]
 [10.]
 [10.]]


# 78. Convert a 1D `numpy` array to `list`

In [79]:
import numpy as np

# 1d array to list
arr = np.array([1, 2, 3])
print(f'NumPy Array:\n{arr}')

list1 = arr.tolist()
print(f'List: {list1}')

NumPy Array:
[1 2 3]
List: [1, 2, 3]


# 79. Convert a Multidimensional `numpy` array to `list`

In [80]:
import numpy as np

# 2d array to list
arr = np.array([[1, 2, 3], [4, 5, 6]])

print(f'NumPy Array:\n{arr}')

list1 = arr.tolist()

print(f'List: {list1}')

NumPy Array:
[[1 2 3]
 [4 5 6]]
List: [[1, 2, 3], [4, 5, 6]]


# 80. Get the `n` largest value of an `array`

In [81]:
Z = np.arange(10000)
np.random.shuffle(Z)
n = 5

nth_largest_value = Z[np.argpartition(-Z,n)[:n]]
print("Nth largest value from an array : ", nth_largest_value)

Nth largest value from an array :  [9999 9998 9997 9995 9996]


# 81. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item)

In [82]:
def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)
    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T
    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]
    return ix
print (cartesian(([1, 2, 3], [4, 5], [6, 7])))

[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


# 82. How to create a record array from a regular array?

In [83]:
Z = np.array([("Hello", 2.5, 3), ("World", 3.6, 2)])
R = np.core.records.fromarrays(Z.T, names='col1, col2, col3', formats = 'S8, f8, i8')
print(R)

[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]


# 83. Consider a large vector Z, compute Z to the power of 3 using `np.power`

In [84]:
x = np.random.random(10000000)
%timeit np.power(x,3)

430 ms ± 9.64 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


# 84. Consider two arrays `A` and `B` of shape `(8,3)` and `(2,2)`. How to find rows of `A` that contain elements of each row of `B` regardless of the order of the elements in `B`

In [85]:
A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))

print("Vector A")
print(A)
print("------------------------------------------------------")
print("Vector B")
print(B)
print("------------------------------------------------------")

C = (A[..., np.newaxis, np.newaxis] == B)
result_rows = (C.sum(axis=(1,2,3)) >= B.shape[1]).nonzero()[0]
print("Result:")
print(result_rows)

Vector A
[[1 4 3]
 [3 3 2]
 [3 2 1]
 [1 3 3]
 [3 1 3]
 [3 0 3]
 [2 1 3]
 [1 4 4]]
------------------------------------------------------
Vector B
[[3 4]
 [2 1]]
------------------------------------------------------
Result:
[0 1 2 3 4 5 6 7]


# 85. Considering a `10x3` matrix, extract rows with unequal values (e.g. `[2,2,3]`)

In [86]:
Z = np.random.randint(0,5,(10,3))
E = np.logical_and.reduce(Z[:,1:] == Z[:,:-1], axis=1)
U = Z[~E]
print(Z)
print(U)

[[0 0 1]
 [4 2 3]
 [4 0 2]
 [1 0 2]
 [3 3 0]
 [3 0 1]
 [4 3 4]
 [0 4 0]
 [3 3 4]
 [1 0 1]]
[[0 0 1]
 [4 2 3]
 [4 0 2]
 [1 0 2]
 [3 3 0]
 [3 0 1]
 [4 3 4]
 [0 4 0]
 [3 3 4]
 [1 0 1]]


# 86. Convert a vector of ints into a matrix binary representation

In [87]:
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128])
print("Initialized array")
print(I)
print("------------------------------------------------------")
B = ((I.reshape(-1,1) & (2**np.arange(8))) != 0).astype(int)
print(B[:,::-1])

Initialized array
[  0   1   2   3  15  16  32  64 128]
------------------------------------------------------
[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


# 87. Extract unique rows from a 2D array

In [88]:
Z = np.random.randint(0,2,(6,3))
T = np.ascontiguousarray(Z).view(np.dtype((np.void, Z.dtype.itemsize * Z.shape[1])))
_, idx = np.unique(T, return_index=True)
uZ = Z[idx]
print(uZ)

[[0 0 1]
 [0 1 0]
 [1 0 1]
 [1 1 0]
 [1 1 1]]


# 88. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function

In [89]:
A = np.array([1, 3, 5, 7, 9, 11, 13, 15, 17])
B = np.array([2, 4, 6, 8, 10, 12, 14, 16, 18])

#Addition, equivalent to np.sum(A)
addition_result = np.einsum('i->', A)
print("Addition result : ", addition_result)

#Multiplication, equivalent to A*B
multiplication_result = np.einsum('i,i->i', A, B)
print("Multiplication result : ", multiplication_result)

#Equivalent to np.inner(A, B)
print("Result : ", np.einsum('i,i', A, B))

#Equivalent to np.outer(A, B)
print("Result : ", np.einsum('i,j', A, B))

Addition result :  81
Multiplication result :  [  2  12  30  56  90 132 182 240 306]
Result :  1050
Result :  [[  2   4   6   8  10  12  14  16  18]
 [  6  12  18  24  30  36  42  48  54]
 [ 10  20  30  40  50  60  70  80  90]
 [ 14  28  42  56  70  84  98 112 126]
 [ 18  36  54  72  90 108 126 144 162]
 [ 22  44  66  88 110 132 154 176 198]
 [ 26  52  78 104 130 156 182 208 234]
 [ 30  60  90 120 150 180 210 240 270]
 [ 34  68 102 136 170 204 238 272 306]]


# 89. Equidistant Samples:
# A Path described by two vectors `(X, Y)`, sample it using `equidistant`

In [90]:
phi = np.arange(0, 10*np.pi, 0.1)
a = 1
x = a*phi*np.cos(phi)
y = a*phi*np.sin(phi)
dr = (np.diff(x)**2 + np.diff(y)**2)**.5 
r = np.zeros_like(x)
r[1:] = np.cumsum(dr) 
r_int = np.linspace(0, r.max(), 200) 
x_int = np.interp(r_int, r, x) 
y_int = np.interp(r_int, r, y)

# 90. Convert a vector of ints into a matrix binary representation using `numpy.unpackbits` function

In [91]:
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128], dtype=np.uint8)
print("Initialized array")
print(I)
print("------------------------------------------------------")
B = np.unpackbits(I[:, np.newaxis], axis=1)
print(B)

Initialized array
[  0   1   2   3  15  16  32  64 128]
------------------------------------------------------
[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


# 91. Convert `numpy` to `pandas dataframe`

In [92]:
import pandas as pd
my_array = np.array([[11,22,33],[44,55,66]])

df = pd.DataFrame(my_array, columns = ['Column_A', 'Column_B', 'Column_C'])

print("Constructed DataFrame:")
print(df)

print("Type of df : ", type(df))

Constructed DataFrame:
   Column_A  Column_B  Column_C
0        11        22        33
1        44        55        66
Type of df :  <class 'pandas.core.frame.DataFrame'>


# 92. Append two `numpy` arrays

In [93]:
array1 = np.arange(5)
array2 = np.arange(4)

print("First Array : ")
print(array1)
print("------------------------------------------------------")

print("Second Array : ")
print(array2)
print("------------------------------------------------------")

array3 = np.append(array1, array2)
print("Append result : ", array3)

First Array : 
[0 1 2 3 4]
------------------------------------------------------
Second Array : 
[0 1 2 3]
------------------------------------------------------
Append result :  [0 1 2 3 4 0 1 2 3]


# 93. Convert `numpy` to `tuple`

In [94]:
array = np.array(((2,2),(2,-2)))
print("Initialized Array : ")
print(array)
print("The shape of an initialized array : ", array.shape)

result = tuple(map(tuple, array))
print("After converting to tuple : ", result)
print("Type of the converted result : ", type(result))

Initialized Array : 
[[ 2  2]
 [ 2 -2]]
The shape of an initialized array :  (2, 2)
After converting to tuple :  ((2, 2), (2, -2))
Type of the converted result :  <class 'tuple'>


# 94. `numpy.where` function

In [95]:
#The numpy.where() function returns the indices of elements in an input array where the given condition is satisfied.

np.where([[True, False], [True, True]], [[1, 2], [3, 4]], [[5, 6], [7, 8]])

array([[1, 6],
       [3, 4]])

# 95. `numpy.where` element wise condition

In [96]:
array_a = np.array([[1, 2, 3], [4, 5, 6]])
print("Initialized Array : ")
print(array_a)
print("------------------------------------------------------")
print("Indices of elements less than 4")
result_indices = np.where(array_a < 4)
print(result_indices)
print("------------------------------------------------------")
print("Elements which are <4")
print(array_a[result_indices])

Initialized Array : 
[[1 2 3]
 [4 5 6]]
------------------------------------------------------
Indices of elements less than 4
(array([0, 0, 0], dtype=int64), array([0, 1, 2], dtype=int64))
------------------------------------------------------
Elements which are <4
[1 2 3]


# 96. Change the sign of a `float` in place

In [97]:
Z = np.random.uniform(-1.0,1.0,100)
print("Initialized Array ")
print(Z)
print("------------------------------------------------------")
print("Result after negation")
result = np.logical_not(Z, out=Z)
print(result)

Initialized Array 
[-0.34516318  0.80014851 -0.16169106 -0.04619318 -0.74179261 -0.54105662
  0.80540289 -0.46311621 -0.70613809 -0.96981911 -0.54517793 -0.98802192
  0.30680648 -0.40172581  0.40350349  0.52892047 -0.18436784 -0.07175675
  0.52422376  0.18842291  0.07889794  0.0948806   0.58853009  0.11765263
  0.32286339 -0.59781554  0.18347588 -0.11936851 -0.55916007  0.28880713
  0.21941255 -0.62746234  0.91162108 -0.90270978  0.81852604  0.93802646
 -0.78408044  0.67969089 -0.65450075 -0.95209683 -0.41168882  0.98971012
  0.52091706 -0.65347938  0.29084728 -0.59189247 -0.89437767  0.65146442
  0.23671913 -0.51749179 -0.20364076 -0.08164564 -0.37687288  0.59305599
  0.17553952 -0.47260853 -0.34411897 -0.08406206  0.48196634  0.03321039
  0.39495615 -0.68651552 -0.73356712  0.06206275 -0.24762826 -0.60169561
 -0.84918842  0.73326218 -0.54589267 -0.80310744 -0.2824881   0.35307565
 -0.67777508 -0.99808703  0.64203301  0.30098685 -0.66849587 -0.1523959
 -0.16844496 -0.55949263  0.03805

# 97. Consider a large vector Z, compute Z to the power of 3 using `arithmetic` operation

In [98]:
x = np.random.random(10000000)
%timeit x*x*x

98.4 ms ± 1.06 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


# 98. Consider a large vector Z, compute Z to the power of 3 using `numpy` `einsum` function

In [99]:
x = np.random.random(10000000)
%timeit np.einsum('i,i,i->i',x,x,x)

52.6 ms ± 519 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


# 99. `numpy.any()` The `numpy.any()` function tests whether any array elements along the mentioned axis evaluate to `True`

In [100]:
#Axis = NONE
print("Boolean Value with axis = NONE  : ", np.any([[True,False],[True,True]]))

#Axis = 0
print("Boolean Value with axis = 0  : ", np.any([[True,False],[True,True]], axis = 0))

print("Boolean value for : ", np.any([-1, 4, 5]))

Boolean Value with axis = NONE  :  True
Boolean Value with axis = 0  :  [ True  True]
Boolean value for :  True


# 100. The `numpy.not_equal()` checks whether two element or unequal or not

In [101]:
a  = np.not_equal([1., 2.], [1., 3.])
print("Not equal : \n", a, "\n")
 
b = np.not_equal([1, 2], [[1, 3],[1, 4]])
print("Not equal : \n", b, "\n")

Not equal : 
 [False  True] 

Not equal : 
 [[False  True]
 [False  True]] 

